#!/usr/bin/env php
<?php

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

//bootstrap
Yii::setAlias('@controllers', __DIR__ . '/controllers');
Yii::setAlias('@components', __DIR__ . '/components');

$config = require(__DIR__ . '/config.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
